# Generated by Django 5.2.8 on 2026-04-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_donation_image_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
