# Generated by Django 5.2.8 on 2026-04-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0007_alter_donation_status_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
