# Generated by Django 5.2.8 on 2026-04-24 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0008_donation_email_donation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready for Pickup'), ('Picked', 'Picked'), ('Distributed', 'Distributed'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='distribution/')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.donation')),
            ],
        ),
    ]
