# Generated by Django 5.2.8 on 2026-04-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0009_alter_donation_status_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
